Update whats_HUP.py
FIX SyntaxError caused by missing argument

> cd ~/education/python/library/signal && hup.py
  File "hup.py", line 26
    print('\n{line}'.format(line=))
                                 ^
SyntaxError: invalid syntax