Update whats_HUP.py
FIX another typo that caused an IndexError. Note to self. MUST TEST CHANGES before committing.

> cd ~/education/python/library/signal && hup.py
send me (pid 1885) a SIGHUPTraceback (most recent call last):
  File "hup.py", line 25, in <module>
    message = lines[1].strip() if lines else "No previous HUP history saved"
IndexError: list index out of range